baseURL = "https://particl.page/"
languageCode = "en-us"
title = "Particl.page"

# Allows for automatic "last modified" for articles etc. (https://gohugo.io/variables/git/)
enableGitInfo = false

# Show all pages by default in this menu (if disabled, define menu location and weight for each page manually)
#sectionPagesMenu = main

# https://gohugo.io/content-management/urls/
[permalinks]
  post = "/:sections/:slug/"
  ecosystem = "/:sections/:slug/"

[params]
  # SEO & Open:graph meta
  siteDescription = "Community-run site around privacy-focused crypto Particl Project"
  siteImage = "images/particl_basics-poster.jpg" # 1200 × 630 px image in /static folder
  siteVersion = "3.0"

  # displays in footer's copyright (until this year)
  copyrightSince = 2018

  # Global social links (via partials/social-follow.html)
  facebook = ""
  twitter = "https://twitter.com/particl_page"
  medium = "https://medium.com/particl-page"
  instagram = ""
  youtube = ""
  github = "https://github.com/particl-page"
  gitlab = ""
  linkedin = ""
  mastodon = "https://mstdn.social/@particl_page"
  slack = ""
  stackoverflow = ""

  # Authors (for microformats.io)
  [params.authors]
    name = "xe-non"
    email = "xe-non@particl.page"
    #image = 


# -- Taxonimies definitions (in format = "singular = plural")
# If you don't want to use them, replace them with:
# disableKinds:
#  - taxonomy
#  - term
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[frontmatter]
  date = ["date", "publishDate"]
  lastmod = ["lastmod"]
  publishDate = ["publishDate", "date"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
