baseURL = "https://dev.particl.page/"
languageCode = "en-us"
title = "Particl.page"
#theme = "particl-page"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
#publishDir = "docs" # for compatibility with GitHub Pages, where generated site will be placed and published

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Community-run site around privacy-focused crypto project Particl.io"
  facebook = ""
  twitter = "https://twitter.com/particl_page"
  medium = "https://medium.com/particl-page"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  show_reading_time = true
  #body_classes = "sans-serif bg-near-white"
  post_content_classes = "sans-serif"
  featured_image = "/images/particl-basics/particl_basics-poster.jpg"
  recent_posts_number = 3
  custom_css = ["particl-page.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
