baseURL = "https://particl.page/"
languageCode = "en-us"
title = "Particl.page"

# Allows for automatic "last modified" for articles etc. (https://gohugo.io/variables/git/)
enableGitInfo = true

# Show all pages by default in this menu (if disabled, define menu location and weight for each page manually)
#sectionPagesMenu = main

# https://gohugo.io/content-management/urls/
[permalinks]
  post = "/:sections/:slug/"
  project = "/:sections/:slug/"

[params]
  # SEO & Open:graph meta
  siteDescription = "Community-run site around privacy-focused crypto Particl Project"
  siteImage = "images/open-graph-img.png" # 1200 × 630 px image in /static folder

  # displays in footer's copyright (until this year)
  copyrightSince = 2018

  # Global social links (via partials/social-follow.html)
  facebook = ""
  twitter = "https://twitter.com/particl_page"
  medium = "https://medium.com/particl-page"
  instagram = ""
  youtube = ""
  github = "https://github.com/particl-page"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""

  # Authors (for microformats.io)
  [params.authors]
    name = "xe-non"
    email = "xe-non@particl.page"
    #image = 


# -- Taxonimies definitions (in format = "singular = plural")
# If you don't want to use them, replace them with:
# disableKinds:
#  - taxonomy
#  - term
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


# Default language
DefaultContentLanguage = "en"
# https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1
    [languages.en.params]
      #AboutPage = /about/
    # https://gohugo.io/content-management/taxonomies/
    [languages.en.taxonomies]
      category = "categories"
      series = "series"
      tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
